### ISSUE TITLE
ABRicate database name is NCBI instead of ncbi

### ISSUE THREAD

**Issue by boasvdp** [Casperjamin/Plasmidsimilarity#7]
When downloading ABRicate to use in Plasmidsimilarity, the NCBI database is downloaded as `ncbi`. In the Snakefile a dictionary is defined which uses `NCBI` instead of lowercase `ncbi`, which causes ABRicate to throw an error

**Comment by Casperjamin** [comment]
cheers boas!
fixed in 6ed8500952f26313c73376325805319226798d78
