### ISSUE TITLE
Forced Numpy version in conda environment file

### ISSUE THREAD

**Issue by boasvdp** [Casperjamin/Plasmidsimilarity#8]
In the conda environment yaml (`envs/plasmidsimilarity.yaml`), numpy is forced to be version 1.13 (Python 2.7). This might make the conda installation a bit slower as well, as a lot of other dependencies don't play well with this. In the `setup.py`, version 1.13 is not forced for numpy

**Comment by Casperjamin** [comment]
fixed see #9
