### ISSUE TITLE
update conda environment definition

### ISSUE THREAD

**Issue by Casperjamin** [Casperjamin/Plasmidsimilarity#9]
see title, and don't forget Abricate

**Comment by boasvdp** [comment]
I exported this environment yaml which works for me and needs much less conda solving, can be installed with `conda env create -f plasmidsimilarity_full.txt`

[plasmidsimilarity_full.txt](https://github.com/Casperjamin/Plasmidsimilarity/files/4889341/plasmidsimilarity_full.txt)

**Comment by Casperjamin** [comment]
I recently have had some time to get back to working on plasmid genomics.

Installation has been fixed, easiest way to install now is from the root directory to:
`pip install .`
afterwards Plasmidsimilarity can be called anywhere from the terminal as:
`Plasmidsimilarity`

future plans are to make the entire workflow installable via conda install
